// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	big "math/big"
	reflect "reflect"

	repositories "github.com/corerid/backend-test/repositories"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryI is a mock of RepositoryI interface.
type MockRepositoryI struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryIMockRecorder
}

// MockRepositoryIMockRecorder is the mock recorder for MockRepositoryI.
type MockRepositoryIMockRecorder struct {
	mock *MockRepositoryI
}

// NewMockRepositoryI creates a new mock instance.
func NewMockRepositoryI(ctrl *gomock.Controller) *MockRepositoryI {
	mock := &MockRepositoryI{ctrl: ctrl}
	mock.recorder = &MockRepositoryIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryI) EXPECT() *MockRepositoryIMockRecorder {
	return m.recorder
}

// CreateTransactionRepo mocks base method.
func (m *MockRepositoryI) CreateTransactionRepo(transaction repositories.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionRepo", transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactionRepo indicates an expected call of CreateTransactionRepo.
func (mr *MockRepositoryIMockRecorder) CreateTransactionRepo(transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionRepo", reflect.TypeOf((*MockRepositoryI)(nil).CreateTransactionRepo), transaction)
}

// GetTransactionRepo mocks base method.
func (m *MockRepositoryI) GetTransactionRepo(address string, startBlock, endBlock *big.Int, cursorID int64, limit int) ([]repositories.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionRepo", address, startBlock, endBlock, cursorID, limit)
	ret0, _ := ret[0].([]repositories.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionRepo indicates an expected call of GetTransactionRepo.
func (mr *MockRepositoryIMockRecorder) GetTransactionRepo(address, startBlock, endBlock, cursorID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionRepo", reflect.TypeOf((*MockRepositoryI)(nil).GetTransactionRepo), address, startBlock, endBlock, cursorID, limit)
}
